package com.org.startup.entity;


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.org.startup.entity.enums.InvitationStatus;



/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users")
public class User implements java.io.Serializable {

	private static final long serialVersionUID = 8167779603327526607L;
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int id;
	private String username;
	private String password;
	private String email;
	private String mobile;

	private InvitationStatus status;
	private Set<UsersRoles> usersRoleses = new HashSet<UsersRoles>(0);

	public User() {
	}

	public User(String username, String password, int id) {
		this.username = username;
		this.password = password;
		this.id = id;
	}
	

	public User(String username, String password, InvitationStatus status) {
		this.username = username;
		this.password = password;
		this.status = status;
	}
	
	public User(String username, String password, int id,InvitationStatus status) {
		this.username = username;
		this.password = password;
		this.id = id;
		this.status = status;
	}

	public User(String username, String password, int id, Set<UsersRoles> usersRoleses) {
		this.username = username;
		this.password = password;
		this.id = id;
		this.usersRoleses = usersRoleses;
	}

	public User(String username, String password, InvitationStatus status,Set<UsersRoles> usersRoleses) {
		this.username = username;
		this.password = password;
		this.status = status;
		this.usersRoleses = usersRoleses;
	}
	@Id
	@Column(name = "username", unique = true, nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}
	
	public void setEmail(String email) {
		this.email = email;
	}
	
	@Column(name = "mobile", nullable = false)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	
	@Column(name = "status", nullable = false)
	public InvitationStatus getStatus() {
		if(this.status == null ||this.status.equals(InvitationStatus.NOTVERIFIED)) {
			return InvitationStatus.NOTVERIFIED;
		}
		return InvitationStatus.VERIFIED;
	}
	
	public void setStatus(InvitationStatus status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UsersRoles> getUsersRoleses() {
		return this.usersRoleses;
	}

	public void setUsersRoleses(Set<UsersRoles> usersRoleses) {
		this.usersRoleses = usersRoleses;
	}

}
